version: '3.3'

services:
  frontend:
    build: frontend
    image: codingmoh/stremlit_style_tf_fe
    ports:
      - 80:${STREAMLIT_SERVER_PORT:-80}
    environment:
      - APP_BACKEND_URL=http://backend
      - STREAMLIT_SERVER_PORT=${STREAMLIT_SERVER_PORT:-80}
    depends_on:
      - backend

  backend:
    build: backend
    image: codingmoh/fastapi_style_tf
    ports:
      - 8080:80