version: '3.3'

services:
  streamlit:
    build: streamlit
    image: codingmoh/streamlit_app
    ports:
      - 80:${STREAMLIT_SERVER_PORT:-80}
    environment:
      - STREAMLIT_SERVER_PORT=${STREAMLIT_SERVER_PORT:-80}